name: release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The tag to release"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_REF: ${{ github.event_name == 'push' && github.ref_name || inputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.RELEASE_REF }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.RELEASE_REF }}
          files: |
            dist/docker-scout_*
